// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDafStxB3amOAIsoCNuIv53kCcS67LgQWU',
    appId: '1:203804359644:web:80d55ebc4c1a162f48ad19',
    messagingSenderId: '203804359644',
    projectId: 'whisper-3312d',
    authDomain: 'whisper-3312d.firebaseapp.com',
    storageBucket: 'whisper-3312d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJbA6RMVFHknBpzx3KcxfpYVjDnDtUgjs',
    appId: '1:203804359644:android:f62bef2e5dd52a0748ad19',
    messagingSenderId: '203804359644',
    projectId: 'whisper-3312d',
    storageBucket: 'whisper-3312d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7cfAKSrX4p0APOi385PpoLg1K4Y9uqgM',
    appId: '1:203804359644:ios:7eb6356a5e03008a48ad19',
    messagingSenderId: '203804359644',
    projectId: 'whisper-3312d',
    storageBucket: 'whisper-3312d.appspot.com',
    iosBundleId: 'com.example.whisper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7cfAKSrX4p0APOi385PpoLg1K4Y9uqgM',
    appId: '1:203804359644:ios:7eb6356a5e03008a48ad19',
    messagingSenderId: '203804359644',
    projectId: 'whisper-3312d',
    storageBucket: 'whisper-3312d.appspot.com',
    iosBundleId: 'com.example.whisper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDafStxB3amOAIsoCNuIv53kCcS67LgQWU',
    appId: '1:203804359644:web:2bda485919383c1148ad19',
    messagingSenderId: '203804359644',
    projectId: 'whisper-3312d',
    authDomain: 'whisper-3312d.firebaseapp.com',
    storageBucket: 'whisper-3312d.appspot.com',
  );
}
